import type { Metadata, Viewport } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "sonner";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

const SITE_URL = "https://www.thenorthbridgemi.com";
const SITE_NAME = "Northbridge Digital";

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 5,
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#0a0a0a" },
    { media: "(prefers-color-scheme: dark)", color: "#0a0a0a" },
  ],
};

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: "Northbridge Digital — Build. Launch. Grow.",
    template: "%s | Northbridge Digital",
  },
  description:
    "Northbridge Digital helps businesses build, launch, and grow online through websites, SEO, social media, and modern digital systems.",
  applicationName: SITE_NAME,
  icons: {
    icon: [
      { url: "/favicon.ico", sizes: "any" },
      { url: "/icon.svg", type: "image/svg+xml" },
    ],
    apple: { url: "/apple-touch-icon.png", sizes: "180x180" },
  },
  manifest: "/manifest.json",
  openGraph: {
    type: "website",
    locale: "en_US",
    url: SITE_URL,
    siteName: SITE_NAME,
    title: "Northbridge Digital — Build. Launch. Grow.",
    description:
      "Human-led digital growth company. Websites, SEO, social media, and digital systems. Packages from $199/mo.",
    // OG image auto-generated by opengraph-image.tsx at route level
  },
  twitter: {
    card: "summary_large_image",
    title: "Northbridge Digital — Build. Launch. Grow.",
    description:
      "Human-led digital growth company. Websites, SEO, social media, and digital systems.",
    creator: "@NorthbridgeDigi",
    // Twitter image auto-generated by twitter-image.tsx at route level
  },
  robots: {
    index: true,
    follow: true,
  },
  verification: {
    // Add your verification codes when ready:
    // google: "your-google-verification-code",
    // yandex: "your-yandex-verification-code",
  },
  other: {
    "msapplication-TileColor": "#0a0a0a",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`dark ${inter.variable}`}>
      <head>
        {/* Preconnect to external domains for speed */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
      </head>
      <body className="min-h-screen bg-background font-sans antialiased">
        {children}
        <Toaster
          theme="dark"
          position="top-right"
          toastOptions={{
            style: {
              background: "#111",
              border: "1px solid #333",
              color: "#fff",
            },
          }}
        />
      </body>
    </html>
  );
}
