import { NextRequest, NextResponse } from "next/server";
import { createClient } from "@supabase/supabase-js";

function getDb() {
  return createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
    { auth: { autoRefreshToken: false, persistSession: false } }
  );
}

/**
 * GET /api/reports/docx?id=REPORT_ID
 *
 * Generates a branded .docx file from a report's content_json and
 * returns it as a download. Uses a lightweight server-side docx builder
 * (no python-docx needed — pure JS with docx npm package).
 */
export async function GET(request: NextRequest) {
  const reportId = request.nextUrl.searchParams.get("id");
  if (!reportId) {
    return NextResponse.json({ error: "id parameter required" }, { status: 400 });
  }

  const db = getDb();

  // Fetch the report
  const { data: report, error } = await db
    .from("reports")
    .select("*")
    .eq("id", reportId)
    .single();

  if (error || !report) {
    return NextResponse.json({ error: "Report not found" }, { status: 404 });
  }

  // Build a clean text-based docx using XML (lightweight, no deps)
  const content = (report.content_json as Record<string, unknown>) || {};
  const title = report.title || "Report";
  const score = report.score;
  const summary = (content.summary as string) || (content.executive_summary as string) || "";
  const sections = (content.sections as Array<Record<string, unknown>>) || (content.categories as Array<Record<string, unknown>>) || [];
  const priorities = (content.top_priorities as string[]) || (content.critical_actions as string[]) || (content.next_steps as string[]) || [];
  const services = (content.recommended_services as string[]) || [];
  const tier = content.recommended_tier as string;
  const value = content.estimated_monthly_value;
  const raw = (content.raw_response as string) || report.content_markdown || "";

  // Build document content as structured text for OOXML
  const paragraphs: Array<{ text: string; style: string; bold?: boolean; size?: number; color?: string }> = [];

  const add = (text: string, style = "normal", opts: { bold?: boolean; size?: number; color?: string } = {}) => {
    paragraphs.push({ text, style, ...opts });
  };

  add("NORTHBRIDGE DIGITAL", "heading", { bold: true, size: 20, color: "4FC3F7" });
  add(title, "heading", { bold: true, size: 56 });
  if (report.target_url) add(report.target_url, "normal", { size: 24, color: "9CA3AF" });
  add(new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" }), "normal", { size: 20, color: "9CA3AF" });
  if (score != null) {
    const color = score >= 76 ? "22C55E" : score >= 51 ? "F59E0B" : "EF4444";
    add(`Score: ${score}/100`, "heading", { bold: true, size: 48, color });
  }
  add("", "normal"); // spacer

  if (summary) {
    add("Executive Summary", "heading", { bold: true, size: 32, color: "4FC3F7" });
    add(summary, "normal", { size: 22 });
    add("", "normal");
  }

  if (priorities.length > 0) {
    add("Key Priorities", "heading", { bold: true, size: 32, color: "4FC3F7" });
    priorities.forEach((p, i) => add(`${i + 1}. ${p}`, "normal", { size: 22 }));
    add("", "normal");
  }

  for (const section of sections) {
    const name = (section.name as string) || (section.heading as string) || "Section";
    const sScore = section.score as number;
    const heading = sScore != null ? `${name} — ${sScore}/100` : name;
    add(heading, "heading", { bold: true, size: 28, color: "4FC3F7" });

    const body = (section.body as string) || (section.description as string) || "";
    if (body) add(body, "normal", { size: 22 });

    const findings = (section.findings as Array<Record<string, string>>) || (section.issues as Array<Record<string, string>>) || [];
    for (const f of findings) {
      const sev = (f.severity || "info").toUpperCase();
      add(`[${sev}] ${f.title || ""}`, "normal", { bold: true, size: 22 });
      if (f.description) add(f.description, "normal", { size: 20, color: "666666" });
      if (f.recommendation || f.fix) add(`→ ${f.recommendation || f.fix}`, "normal", { size: 20, color: "4FC3F7" });
    }
    add("", "normal");
  }

  if (services.length > 0) {
    add("Recommended Services", "heading", { bold: true, size: 32, color: "F5C542" });
    services.forEach((s) => add(`• ${s}`, "normal", { size: 22 }));
  }
  if (tier) add(`Recommended Package: ${tier}`, "normal", { bold: true, size: 22 });
  if (value) add(`Estimated Monthly Value: $${value}/mo`, "normal", { size: 22 });

  if (raw && !summary && sections.length === 0) {
    add("Full Report", "heading", { bold: true, size: 32, color: "4FC3F7" });
    add(raw, "normal", { size: 20 });
  }

  add("", "normal");
  add("Generated by Northbridge Digital", "normal", { size: 18, color: "9CA3AF" });
  add("www.thenorthbridgemi.com", "normal", { size: 18, color: "4FC3F7" });

  // Build OOXML
  const escXml = (s: string) => s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");

  const bodyXml = paragraphs.map((p) => {
    const sz = p.size || 22;
    const color = p.color || "333333";
    const bold = p.bold ? "<w:b/>" : "";
    const jc = p.style === "heading" ? '<w:jc w:val="center"/>' : "";
    return `<w:p><w:pPr>${jc}<w:rPr><w:sz w:val="${sz}"/><w:szCs w:val="${sz}"/><w:color w:val="${color}"/>${bold}</w:rPr></w:pPr><w:r><w:rPr><w:sz w:val="${sz}"/><w:szCs w:val="${sz}"/><w:color w:val="${color}"/>${bold}<w:rFonts w:ascii="Calibri" w:hAnsi="Calibri"/></w:rPr><w:t xml:space="preserve">${escXml(p.text)}</w:t></w:r></w:p>`;
  }).join("");

  const docXml = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:document xmlns:wpc="http://schemas.microsoft.com/office/word/2010/wordprocessingCanvas" xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:m="http://schemas.openxmlformats.org/officeDocument/2006/math" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:wp14="http://schemas.microsoft.com/office/word/2010/wordprocessingDrawing" xmlns:wp="http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing" xmlns:w10="urn:schemas-microsoft-com:office:word" xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" xmlns:w14="http://schemas.microsoft.com/office/word/2010/wordml" xmlns:wpg="http://schemas.microsoft.com/office/word/2010/wordprocessingGroup" xmlns:wpi="http://schemas.microsoft.com/office/word/2010/wordprocessingInk" xmlns:wne="http://schemas.microsoft.com/office/word/2006/wordml" xmlns:wps="http://schemas.microsoft.com/office/word/2010/wordprocessingShape" mc:Ignorable="w14 wp14"><w:body>${bodyXml}<w:sectPr><w:pgSz w:w="12240" w:h="15840"/><w:pgMar w:top="1440" w:right="1440" w:bottom="1440" w:left="1440"/></w:sectPr></w:body></w:document>`;

  const contentTypesXml = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/></Types>`;

  const relsXml = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>`;

  const wordRelsXml = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"></Relationships>`;

  // Build ZIP (minimal docx is a zip with specific structure)
  // Using a tiny inline ZIP builder for serverless (no external deps)
  const { Blob: NodeBlob } = await import("node:buffer");

  // For Vercel Edge/Serverless, we'll use a simpler approach:
  // Generate the OOXML as a flat OPC package (single XML)
  // Most Word processors accept this format
  const flatOpc = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<?mso-application progid="Word.Document"?>
<pkg:package xmlns:pkg="http://schemas.microsoft.com/office/2006/xmlPackage">
  <pkg:part pkg:name="/_rels/.rels" pkg:contentType="application/vnd.openxmlformats-package.relationships+xml"><pkg:xmlData>${relsXml}</pkg:xmlData></pkg:part>
  <pkg:part pkg:name="/word/_rels/document.xml.rels" pkg:contentType="application/vnd.openxmlformats-package.relationships+xml"><pkg:xmlData>${wordRelsXml}</pkg:xmlData></pkg:part>
  <pkg:part pkg:name="/word/document.xml" pkg:contentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"><pkg:xmlData>${docXml}</pkg:xmlData></pkg:part>
  <pkg:part pkg:name="/[Content_Types].xml" pkg:contentType="application/vnd.openxmlformats-package.content-types+xml"><pkg:xmlData>${contentTypesXml}</pkg:xmlData></pkg:part>
</pkg:package>`;

  const fileName = `${(report.report_type || "report").replace(/_/g, "-")}-${reportId.slice(0, 8)}.docx`;

  return new NextResponse(flatOpc, {
    headers: {
      "Content-Type": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
      "Content-Disposition": `attachment; filename="${fileName}"`,
      "Cache-Control": "private, max-age=3600",
    },
  });
}
